spring:
  reactor:
    debug-agent:
      enabled: false
  rabbitmq:
    host: webhookie-amqp
    virtual-host: webhookie
    username: webhookie-admin
    password: AdminP@XX
  devtools:
    add-properties: false
